# List of all companies listed on stock market

[good]
name = "Good Stock exchange"
code = "GOOD"
max_companies = 10.0

[good.vcrp]
name = "Villager Corporation"
code = "VCRP"
number_of_stocks = 10.0
owner_stocks = 5.0
price_per_stock = 1.0
